# 游戏窗口类名和窗口标题
game-window: [ 'UnityWndClass', '原神' ]

# 使用 Alpha 通道的值提高检测准确度，会带来一定性能开销
# [!] 某些旧版显卡可能无法使用此功能，如果适配出现问题请将该项设置为 False 并更换模板
use-alpha: True

# 强制将所有颜色转换为灰色，在 Alpha 模式无法使用时可能按需开启
gray-only: False
